(function(){
  const $=s=>document.querySelector(s);let db=StayAtlas.load();let selectedId=db.hotels[0]?.id||null;
  function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function parseBool(raw){if(!raw)return null;if(/^[〇◯○]|あり|有/.test(raw))return true;if(/^×|なし|アクセス権なし/.test(raw))return false;return null;}
  function parseCapacity(raw){const m=(raw||'').match(/(\d+)人/);return m?Number(m[1]):null;}
  function parseChild(raw){const s=(raw||'').trim();const m=s.match(/(\d+)歳まで/);if(m)return{raw:s,allowed:true,rule_type:'age',max_age:Number(m[1])};if(/未就学児/.test(s))return{raw:s,allowed:true,rule_type:'preschool',max_age:null};if(/小学生/.test(s))return{raw:s,allowed:true,rule_type:'school_grade',max_age:null};if(/以上のみ宿泊可/.test(s))return{raw:s,allowed:false,rule_type:'minimum_age',max_age:null};if(/指定なし/.test(s))return{raw:s,allowed:null,rule_type:'unspecified',max_age:null};return{raw:s,allowed:null,rule_type:s?'free_text':'missing',max_age:null};}
  function regionFor(pref){return StayAtlas.regions[pref]||'';}
  function renderList(){const q=$('#adminSearch').value.toLowerCase();const rows=db.hotels.filter(h=>[h.name_ja,h.name_en,h.prefecture,h.chain].join(' ').toLowerCase().includes(q));$('#adminRecords').innerHTML=rows.map(h=>`<button class="admin-record ${h.id===selectedId?'is-active':''}" data-id="${esc(h.id)}"><strong>${esc(h.name_ja||'名称未登録')}</strong><br><small>${esc(h.prefecture||'—')} / ${esc(h.chain||'—')} / ${esc(h.quality)}</small></button>`).join('');$('#adminCount').textContent=`${db.hotels.length} hotels`;document.querySelectorAll('.admin-record').forEach(b=>b.addEventListener('click',()=>{selectedId=b.dataset.id;fill();renderList();renderRevisions();}));}
  function current(){return db.hotels.find(h=>h.id===selectedId);}
  function fill(){const h=current();if(!h)return;$('#f_id').value=h.id;$('#f_name_ja').value=h.name_ja||'';$('#f_name_en').value=h.name_en||'';$('#f_chain').value=h.chain||'Marriott Bonvoy';$('#f_brand').value=h.brand||'';$('#f_prefecture').value=h.prefecture||'';$('#f_city').value=h.city||'';$('#f_child').value=h.child?.raw||'';$('#f_capacity').value=h.capacity?.raw||'';$('#f_award').value=h.award?.raw||'';$('#f_lounge').value=h.facilities?.lounge?.raw||'';$('#f_breakfast').value=h.facilities?.breakfast?.raw||'';$('#f_onsen').value=h.facilities?.onsen?.raw||'';$('#f_pool').value=h.facilities?.pool?.raw||'';$('#f_parking').value=h.facilities?.parking?.raw||'';$('#f_quality').value=h.quality||'unverified';$('#f_checked').value=h.source?.last_checked||'';$('#f_source_url').value=h.source?.url||'';$('#f_note').value='';}
  function buildNext(){const old=current();const lounge=$('#f_lounge').value.trim(),breakfast=$('#f_breakfast').value.trim(),onsen=$('#f_onsen').value.trim(),pool=$('#f_pool').value.trim(),parking=$('#f_parking').value.trim();return {...StayAtlas.clone(old),name_ja:$('#f_name_ja').value.trim(),name_en:$('#f_name_en').value.trim(),chain:$('#f_chain').value,brand:$('#f_brand').value.trim(),prefecture:$('#f_prefecture').value.trim(),region:regionFor($('#f_prefecture').value.trim()),city:$('#f_city').value.trim(),child:parseChild($('#f_child').value),capacity:{raw:$('#f_capacity').value.trim(),value:parseCapacity($('#f_capacity').value)},award:{raw:$('#f_award').value.trim()},facilities:{lounge:{raw:lounge,available:parseBool(lounge)},breakfast:{raw:breakfast,has_info:Boolean(breakfast)},onsen:{raw:onsen,available:parseBool(onsen)},pool:{raw:pool,available:parseBool(pool)},parking:{raw:parking,has_info:Boolean(parking)}},quality:$('#f_quality').value,source:{...(old.source||{}),label:old.source?.label||'Admin edit',url:$('#f_source_url').value.trim(),last_checked:$('#f_checked').value||null}};}
  function renderRevisions(){const revs=StayAtlas.loadRevisions().filter(r=>r.hotelId===selectedId);if(!revs.length){$('#revisionList').innerHTML='<p class="muted">まだRevisionはありません。</p>';return;}$('#revisionList').innerHTML=revs.map(r=>`<div class="revision"><strong>${esc(r.action)}</strong> <small>${esc(new Date(r.timestamp).toLocaleString('ja-JP'))}</small><p>${esc(r.note||'')}</p><button class="secondary-btn restore-btn" data-rev="${esc(r.id)}" type="button">この状態を復元</button></div>`).join('');document.querySelectorAll('.restore-btn').forEach(b=>b.addEventListener('click',()=>{if(!confirm('このRevisionの内容を現在値として復元します。現在値も履歴に残ります。'))return;StayAtlas.restoreRevision(b.dataset.rev);db=StayAtlas.load();fill();renderList();renderRevisions();}));}
  $('#saveBtn').addEventListener('click',()=>{if(!selectedId)return;const next=buildNext();StayAtlas.updateHotel(selectedId,next,$('#f_note').value.trim()||'Admin edit');db=StayAtlas.load();fill();renderList();renderRevisions();alert('保存しました。変更前の状態はRevisionに保持されています。');});
  $('#adminSearch').addEventListener('input',renderList);
  $('#resetBtn').addEventListener('click',()=>{if(!confirm('このブラウザ内の編集・履歴を削除してSeedへ戻します。'))return;db=StayAtlas.reset();selectedId=db.hotels[0]?.id||null;renderList();fill();renderRevisions();});
  $('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(StayAtlas.load(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`stay-atlas-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);});
  $('#importBtn').addEventListener('click',()=>{const html=$('#legacyHtml').value;if(!html.trim()){alert('HTMLを貼り付けてください。');return;}if(!confirm('現在のブラウザ内データを、貼り付けた旧WordPress表から作り直します。'))return;try{db=StayAtlas.importLegacyHtml(html);selectedId=db.hotels[0]?.id||null;$('#importResult').textContent=`${db.hotels.length}件を取り込みました。英語名と未確認項目は管理画面から確認してください。`;renderList();fill();renderRevisions();}catch(e){console.error(e);$('#importResult').textContent=`取り込みエラー: ${e.message}`;}});
  renderList();fill();renderRevisions();
})();