(function(){
  const STORAGE_KEY='naojun_stay_atlas_v1';
  const REV_KEY='naojun_stay_atlas_revisions_v1';
  const regions={
    '北海道':'北海道','青森県':'東北','岩手県':'東北','宮城県':'東北','秋田県':'東北','山形県':'東北','福島県':'東北',
    '茨城県':'関東','栃木県':'関東','群馬県':'関東','埼玉県':'関東','千葉県':'関東','東京都':'関東','神奈川県':'関東',
    '新潟県':'中部','富山県':'中部','石川県':'中部','福井県':'中部','山梨県':'中部','長野県':'中部','岐阜県':'中部','静岡県':'中部','愛知県':'中部',
    '三重県':'近畿','滋賀県':'近畿','京都府':'近畿','大阪府':'近畿','兵庫県':'近畿','奈良県':'近畿','和歌山県':'近畿',
    '鳥取県':'中国','島根県':'中国','岡山県':'中国','広島県':'中国','山口県':'中国',
    '徳島県':'四国','香川県':'四国','愛媛県':'四国','高知県':'四国',
    '福岡県':'九州・沖縄','佐賀県':'九州・沖縄','長崎県':'九州・沖縄','熊本県':'九州・沖縄','大分県':'九州・沖縄','宮崎県':'九州・沖縄','鹿児島県':'九州・沖縄','沖縄県':'九州・沖縄'
  };
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function seed(){return clone(window.STAY_ATLAS_SEED||{hotels:[]});}
  function load(){try{const x=localStorage.getItem(STORAGE_KEY);return x?JSON.parse(x):seed();}catch(e){console.warn(e);return seed();}}
  function save(db){localStorage.setItem(STORAGE_KEY,JSON.stringify(db));}
  function loadRevisions(){try{return JSON.parse(localStorage.getItem(REV_KEY)||'[]');}catch(e){return[];}}
  function saveRevisions(r){localStorage.setItem(REV_KEY,JSON.stringify(r));}
  function addRevision(hotelId,action,snapshot,note){const revs=loadRevisions();revs.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random(),hotelId,action,note:note||'',timestamp:new Date().toISOString(),snapshot:clone(snapshot)});saveRevisions(revs);return revs[0];}
  function updateHotel(hotelId,next,note){const db=load();const i=db.hotels.findIndex(h=>h.id===hotelId);if(i<0)throw new Error('Hotel not found');addRevision(hotelId,'edit',db.hotels[i],note||'Admin edit');db.hotels[i]=clone(next);db.updatedAt=new Date().toISOString();save(db);return db.hotels[i];}
  function restoreRevision(revisionId){const revs=loadRevisions();const rev=revs.find(r=>r.id===revisionId);if(!rev)throw new Error('Revision not found');const db=load();const i=db.hotels.findIndex(h=>h.id===rev.hotelId);if(i<0)throw new Error('Hotel not found');addRevision(rev.hotelId,'restore',db.hotels[i],`Restore from ${revisionId}`);db.hotels[i]=clone(rev.snapshot);db.updatedAt=new Date().toISOString();save(db);return db.hotels[i];}
  function reset(){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(REV_KEY);return load();}
  function slugify(s){return (s||'hotel').toLowerCase().normalize('NFKC').replace(/[\s　]+/g,'-').replace(/[^a-z0-9\-ぁ-んァ-ヶ一-龠々ー]/g,'').slice(0,72)||`hotel-${Date.now()}`;}
  function parseBool(raw){if(!raw)return null;const s=raw.trim();if(/^[〇◯○]|あり|有/.test(s))return true;if(/^×|なし|アクセス権なし/.test(s))return false;return null;}
  function parseCapacity(raw){const m=(raw||'').match(/(\d+)人/);return m?Number(m[1]):null;}
  function parseChild(raw){const s=(raw||'').trim();const m=s.match(/(\d+)歳まで/);if(m)return{raw:s,allowed:true,rule_type:'age',max_age:Number(m[1])};if(/未就学児/.test(s))return{raw:s,allowed:true,rule_type:'preschool',max_age:null};if(/小学生/.test(s))return{raw:s,allowed:true,rule_type:'school_grade',max_age:null};if(/以上のみ宿泊可/.test(s))return{raw:s,allowed:false,rule_type:'minimum_age',max_age:null};if(/指定なし/.test(s))return{raw:s,allowed:null,rule_type:'unspecified',max_age:null};return{raw:s,allowed:s?null:null,rule_type:s?'free_text':'missing',max_age:null};}
  function detectQuality(cells){const joined=cells.join(' ');if(!cells[0]||!cells[1]||/[?？]|いける|追加料金？|未確認/.test(joined))return'needs_review';return'unverified';}
  function detectBrand(name,chain){const rules=[['DoubleTree by Hilton',/ダブルツリー|DoubleTree/i],['Conrad',/コンラッド|Conrad/i],['Hilton',/ヒルトン|Hilton/i],['Canopy by Hilton',/キャノピー|Canopy/i],['Waldorf Astoria',/ウォルドーフ|Waldorf/i],['LXR Hotels & Resorts',/LXR/i],['The Ritz-Carlton',/リッツ.?カールトン|Ritz-Carlton/i],['Westin',/ウェスティン|Westin/i],['Sheraton',/シェラトン|Sheraton/i],['Fairfield by Marriott',/フェアフィールド|Fairfield/i],['Courtyard',/コートヤード|Courtyard/i],['Moxy',/モクシー|Moxy/i],['Aloft',/アロフト|Aloft/i],['Marriott',/マリオット|Marriott/i],['W Hotels',/^W大阪|W Osaka/i],['St. Regis',/セントレジス|St\. Regis/i],['Autograph Collection',/オートグラフ|Autograph/i],['Luxury Collection',/ラグジュアリーコレクション|Luxury Collection/i]];for(const [brand,re] of rules){if(re.test(name))return brand;}return chain==='Hilton Honors'?'Hilton portfolio':'Marriott portfolio';}
  function importLegacyHtml(html){const doc=new DOMParser().parseFromString(html,'text/html');const rows=[...doc.querySelectorAll('table tbody tr')];let currentChain='Marriott Bonvoy';const hotels=[];const seen=new Set();for(const tr of rows){const cells=[...tr.querySelectorAll('td')].map(td=>td.textContent.replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim());if(!cells.length||cells.every(x=>!x))continue;const name=cells[0]||'';if(/ヒルトンニセコビレッジ/.test(name))currentChain='Hilton Honors';const prefecture=cells[1]||'';const idBase=slugify(name||`${prefecture}-unknown`);let id=idBase,n=2;while(seen.has(id)){id=`${idBase}-${n++}`;}seen.add(id);const status=/開業予定/.test(name)?'planned':'open';const cleanName=name.replace(/（\d{4}年.*?開業予定）|\(\d{4}年.*?開業予定\)/g,'').trim();const hotel={id,name_ja:cleanName,name_en:'',chain:currentChain,brand:detectBrand(cleanName,currentChain),portfolio:/SLH/i.test(name)?'SLH':'',status,region:regions[prefecture]||'',prefecture,city:'',child:parseChild(cells[2]||''),award:{raw:cells[3]||''},capacity:{raw:cells[4]||'',value:parseCapacity(cells[4]||'')},facilities:{lounge:{raw:cells[5]||'',available:parseBool(cells[5]||'')},breakfast:{raw:cells[6]||'',has_info:Boolean(cells[6])},onsen:{raw:cells[7]||'',available:parseBool(cells[7]||'')},pool:{raw:cells[8]||'',available:parseBool(cells[8]||'')},parking:{raw:cells[9]||'',has_info:Boolean(cells[9])}},source:{label:'pocca.net legacy table',url:'https://pocca.net/check-in/2025/02/01/%e3%83%92%e3%83%ab%e3%83%88%e3%83%b3%e3%83%9b%e3%83%86%e3%83%ab%e3%83%bb%e3%83%9e%e3%83%aa%e3%82%aa%e3%83%83%e3%83%88%e3%83%9b%e3%83%86%e3%83%ab%e3%80%80%e5%ad%90%e9%80%a3%e3%82%8c%e6%97%85%e8%a1%8c/',last_checked:null},quality:detectQuality(cells)};hotels.push(hotel);}const db={schemaVersion:1,importedFrom:'legacy WordPress table via admin importer',updatedAt:new Date().toISOString(),hotels};save(db);saveRevisions([]);return db;}
  window.StayAtlas={load,save,reset,loadRevisions,updateHotel,restoreRevision,addRevision,importLegacyHtml,regions,clone};
})();