(function(){
  const STORAGE_KEY='naojun_stay_atlas_v1';
  const REV_KEY='naojun_stay_atlas_revisions_v1';
  const DATASET_VERSION=2;
  const CURATION_VERSION=Number(window.STAY_ATLAS_CURATED?.version||0);
  const regions={
    '北海道':'北海道','青森県':'東北','岩手県':'東北','宮城県':'東北','秋田県':'東北','山形県':'東北','福島県':'東北',
    '茨城県':'関東','栃木県':'関東','群馬県':'関東','埼玉県':'関東','千葉県':'関東','東京都':'関東','神奈川県':'関東',
    '新潟県':'中部','富山県':'中部','石川県':'中部','福井県':'中部','山梨県':'中部','長野県':'中部','岐阜県':'中部','静岡県':'中部','愛知県':'中部',
    '三重県':'近畿','滋賀県':'近畿','京都府':'近畿','大阪府':'近畿','兵庫県':'近畿','奈良県':'近畿','和歌山県':'近畿',
    '鳥取県':'中国','島根県':'中国','岡山県':'中国','広島県':'中国','山口県':'中国','徳島県':'四国','香川県':'四国','愛媛県':'四国','高知県':'四国',
    '福岡県':'九州・沖縄','佐賀県':'九州・沖縄','長崎県':'九州・沖縄','熊本県':'九州・沖縄','大分県':'九州・沖縄','宮崎県':'九州・沖縄','鹿児島県':'九州・沖縄','沖縄県':'九州・沖縄'
  };
  const trackedFields=[
    ['name_ja','ホテル名'],['name_en','英語名'],['chain','チェーン'],['brand','ブランド'],['status','公開状態'],['opening_note','開業メモ'],['official_url','公式URL'],['prefecture','都道府県'],['city','市区町村'],
    ['child.raw','添寝'],['award.raw','ポイント・宿泊条件'],['capacity.raw','定員'],['facilities.lounge.raw','ラウンジ'],['facilities.breakfast.raw','朝食'],['facilities.onsen.raw','温泉'],['facilities.pool.raw','プール'],['facilities.parking.raw','駐車場'],['quality','品質'],['source.url','Source URL'],['source.last_checked','最終確認日']
  ];
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function seed(){return clone(window.STAY_ATLAS_SEED||{schemaVersion:1,datasetVersion:0,curationVersion:0,hotels:[]});}
  function normalizeDb(db){const next=db&&typeof db==='object'?db:seed();next.schemaVersion=1;next.datasetVersion=Number(next.datasetVersion||0);next.curationVersion=Number(next.curationVersion||0);next.hotels=Array.isArray(next.hotels)?next.hotels:[];return next;}
  function load(){try{const x=localStorage.getItem(STORAGE_KEY);return normalizeDb(x?JSON.parse(x):seed());}catch(e){console.warn(e);return seed();}}
  function save(db){localStorage.setItem(STORAGE_KEY,JSON.stringify(normalizeDb(db)));}
  function hasCurrentDataset(){try{const x=localStorage.getItem(STORAGE_KEY);if(!x)return false;return normalizeDb(JSON.parse(x)).datasetVersion>=DATASET_VERSION;}catch(e){return false;}}
  function loadRevisions(){try{const x=JSON.parse(localStorage.getItem(REV_KEY)||'[]');return Array.isArray(x)?x:[];}catch(e){return[];}}
  function saveRevisions(r){localStorage.setItem(REV_KEY,JSON.stringify(Array.isArray(r)?r:[]));}
  function getPath(obj,path){return path.split('.').reduce((v,k)=>v==null?undefined:v[k],obj);}
  function diffHotel(before,after){return trackedFields.flatMap(([path,label])=>{const a=getPath(before,path);const b=getPath(after,path);return JSON.stringify(a)===JSON.stringify(b)?[]:[{path,label,before:a??'',after:b??''}];});}
  function addRevision(hotelId,action,snapshot,note,changes){const revs=loadRevisions();revs.unshift({id:(globalThis.crypto&&crypto.randomUUID)?crypto.randomUUID():String(Date.now())+Math.random(),hotelId,action,note:note||'',timestamp:new Date().toISOString(),changes:Array.isArray(changes)?changes:[],snapshot:clone(snapshot)});saveRevisions(revs);return revs[0];}
  function updateHotel(hotelId,next,note){const db=load();const i=db.hotels.findIndex(h=>h.id===hotelId);if(i<0)throw new Error('Hotel not found');const before=db.hotels[i];const changes=diffHotel(before,next);if(!changes.length)return before;addRevision(hotelId,'edit',before,note||'Admin edit',changes);db.hotels[i]=clone(next);db.updatedAt=new Date().toISOString();save(db);return db.hotels[i];}
  function restoreRevision(revisionId){const revs=loadRevisions();const rev=revs.find(r=>r.id===revisionId);if(!rev)throw new Error('Revision not found');const db=load();const i=db.hotels.findIndex(h=>h.id===rev.hotelId);if(i<0)throw new Error('Hotel not found');const before=db.hotels[i];addRevision(rev.hotelId,'restore',before,`Restore from ${revisionId}`,diffHotel(before,rev.snapshot));db.hotels[i]=clone(rev.snapshot);db.updatedAt=new Date().toISOString();save(db);return db.hotels[i];}
  function reset(){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(REV_KEY);return seed();}
  function slugify(s){return (s||'hotel').toLowerCase().normalize('NFKC').replace(/[\s　]+/g,'-').replace(/[^a-z0-9\-ぁ-んァ-ヶ一-龠々ー]/g,'').slice(0,72)||`hotel-${Date.now()}`;}
  function parseBool(raw){if(!raw)return null;const s=raw.trim();if(/^[〇◯○]|あり|有/.test(s))return true;if(/^×|なし|アクセス権なし/.test(s))return false;return null;}
  function parseCapacity(raw){const m=(raw||'').match(/(\d+)人/);return m?Number(m[1]):null;}
  function parseChild(raw){const s=(raw||'').trim();const m=s.match(/(\d+)歳まで/);if(m)return{raw:s,allowed:true,rule_type:'age',max_age:Number(m[1])};if(/未就学児/.test(s))return{raw:s,allowed:true,rule_type:'preschool',max_age:null};if(/小学生/.test(s))return{raw:s,allowed:true,rule_type:'school_grade',max_age:null};if(/以上のみ宿泊可/.test(s))return{raw:s,allowed:false,rule_type:'minimum_age',max_age:null};if(/指定なし/.test(s))return{raw:s,allowed:null,rule_type:'unspecified',max_age:null};return{raw:s,allowed:null,rule_type:s?'free_text':'missing',max_age:null};}
  function parseName(raw){let name=String(raw||'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();const opening=name.match(/[（(]([^）)]*開業予定)[）)]/);const status=/開業予定/.test(name)?'planned':'open';let name_en='';const english=name.match(/[（(]([A-Za-z][A-Za-z0-9 ,.&\-]+)[）)]/);if(english&&!/^SLH$/i.test(english[1]))name_en=english[1].trim();name=name.replace(/（\d{4}年.*?開業予定）|\(\d{4}年.*?開業予定\)/g,'').replace(/[（(]SLH[）)]/ig,'').replace(/、?SLHホテル/ig,'').trim();if(name_en)name=name.replace(new RegExp('[（(]'+name_en.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'[）)]'),'').trim();return{name_ja:name.replace(/[、,]\s*$/,''),name_en,status,opening_note:opening?opening[1]:''};}
  function detectQuality(cells){const joined=cells.join(' ');if(!cells[0]||!cells[1]||/[?？]|いける|追加料金？|未確認/.test(joined))return'needs_review';return'unverified';}
  function detectBrand(name,chain){const rules=[['DoubleTree by Hilton',/ダブルツリー|DoubleTree/i],['Conrad',/コンラッド|Conrad/i],['Hilton Garden Inn',/ヒルトン・ガーデン・イン|Hilton Garden Inn/i],['Canopy by Hilton',/キャノピー|Canopy/i],['Waldorf Astoria',/ウォルドーフ|Waldorf/i],['Curio Collection by Hilton',/キュリオ・コレクション|Curio Collection/i],['LXR Hotels & Resorts',/LXR/i],['Hilton',/ヒルトン|Hilton/i],['The Ritz-Carlton',/リッツ.?カールトン|Ritz-Carlton/i],['Westin',/ウェスティン|Westin/i],['Sheraton',/シェラトン|Sheraton/i],['Fairfield by Marriott',/フェアフィールド|フェアフィード|Fairfield/i],['Courtyard',/コートヤード|Courtyard/i],['Moxy',/モクシー|Moxy/i],['Aloft',/アロフト|Aloft/i],['AC Hotels',/^ACホテル|AC Hotel/i],['JW Marriott',/JWマリオット|JW Marriott/i],['Bulgari Hotels & Resorts',/ブルガリホテル|Bulgari Hotel/i],['W Hotels',/^W大阪|W Osaka/i],['St. Regis',/セントレジス|St\. Regis/i],['The EDITION',/エディション|EDITION/i],['Autograph Collection',/オートグラフ|Autograph/i],['Luxury Collection',/ラグジュアリーコレクション|Luxury Collection/i],['Tribute Portfolio',/トリビュートポートフォリオ|Tribute Portfolio/i],['Renaissance',/ルネッサンス|Renaissance/i],['Marriott',/マリオット|Marriott/i]];for(const [brand,re] of rules){if(re.test(name))return brand;}return chain==='Hilton Honors'?'Hilton portfolio':'Marriott portfolio';}
  function deepMerge(target,patch){const out=clone(target||{});Object.entries(patch||{}).forEach(([key,value])=>{if(value&&typeof value==='object'&&!Array.isArray(value)){out[key]=deepMerge(out[key]&&typeof out[key]==='object'?out[key]:{},value);}else{out[key]=clone(value);}});return out;}
  function patchMatches(hotel,match){return Object.entries(match||{}).every(([key,value])=>hotel?.[key]===value);}
  function applyCuratedPatches(db){const curated=window.STAY_ATLAS_CURATED;if(!curated?.patches?.length)return normalizeDb(db);const next=clone(normalizeDb(db));curated.patches.forEach(item=>{const i=next.hotels.findIndex(h=>patchMatches(h,item.match));if(i<0)return;const patched=deepMerge(next.hotels[i],item.patch||{});patched.verifications=deepMerge(patched.verifications||{},item.verifications||{});next.hotels[i]=patched;});next.curationVersion=Number(curated.version||0);next.curatedAt=curated.checkedAt||new Date().toISOString().slice(0,10);return next;}
  function validateHotel(h){const errors=[],warnings=[];if(!h.id)errors.push('id');if(!h.name_ja)warnings.push('name_ja');if(!h.prefecture)warnings.push('prefecture');if(!h.name_en)warnings.push('name_en');if(!h.source?.url&&!Object.keys(h.verifications||{}).length)warnings.push('source');return{valid:errors.length===0,errors,warnings};}
  function health(db){const hotels=(db||load()).hotels||[];const quality={verified:0,unverified:0,needs_review:0,missing:0,conflicting:0};let englishPending=0,sourcePending=0,fieldVerified=0,fieldConflicting=0;hotels.forEach(h=>{quality[h.quality]=(quality[h.quality]||0)+1;if(!h.name_en)englishPending++;const checks=Object.values(h.verifications||{});if(!h.source?.url&&!checks.length)sourcePending++;fieldVerified+=checks.filter(v=>v.status==='verified').length;fieldConflicting+=checks.filter(v=>v.status==='conflicting').length;});return{total:hotels.length,quality,englishPending,sourcePending,fieldVerified,fieldConflicting,invalid:hotels.filter(h=>!validateHotel(h).valid).length};}
  function buildDbFromLegacyHtml(html){const doc=new DOMParser().parseFromString(html,'text/html');const rows=[...doc.querySelectorAll('table tbody tr')];let currentChain='Marriott Bonvoy';const hotels=[];const seen=new Set();for(const tr of rows){const cells=[...tr.querySelectorAll('td')].map(td=>td.textContent.replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim());if(!cells.length||cells.every(x=>!x))continue;while(cells.length<10)cells.push('');const rawName=cells[0]||'';if(/ヒルトンニセコビレッジ/.test(rawName))currentChain='Hilton Honors';const parsed=parseName(rawName);const prefecture=cells[1]||'';const idBase=slugify(parsed.name_ja||`${prefecture}-unknown`);let id=idBase,n=2;while(seen.has(id)){id=`${idBase}-${n++}`;}seen.add(id);hotels.push({id,name_ja:parsed.name_ja,name_en:parsed.name_en,chain:currentChain,brand:detectBrand(parsed.name_ja,currentChain),portfolio:/SLH/i.test(rawName)?'SLH':'',status:parsed.status,opening_note:parsed.opening_note,official_url:'',region:regions[prefecture]||'',prefecture,city:'',child:parseChild(cells[2]||''),award:{raw:cells[3]||''},capacity:{raw:cells[4]||'',value:parseCapacity(cells[4]||'')},facilities:{lounge:{raw:cells[5]||'',available:parseBool(cells[5]||'')},breakfast:{raw:cells[6]||'',has_info:Boolean(cells[6])},onsen:{raw:cells[7]||'',available:parseBool(cells[7]||'')},pool:{raw:cells[8]||'',available:parseBool(cells[8]||'')},parking:{raw:cells[9]||'',has_info:Boolean(cells[9])}},source:{label:'pocca.net legacy table',url:'https://pocca.net/check-in/2025/02/01/%e3%83%92%e3%83%ab%e3%83%88%e3%83%b3%e3%83%9b%e3%83%86%e3%83%ab%e3%83%bb%e3%83%9e%e3%83%aa%e3%82%aa%e3%83%83%e3%83%88%e3%83%9b%e3%83%86%e3%83%ab%e3%80%80%e5%ad%90%e9%80%a3%e3%82%8c%e6%97%85%e8%a1%8c/',last_checked:null},verifications:{},quality:detectQuality(cells)});}return{schemaVersion:1,datasetVersion:DATASET_VERSION,curationVersion:0,importedFrom:'Jun-provided legacy WordPress table',updatedAt:new Date().toISOString(),hotels};}
  function importLegacyHtml(html){const db=applyCuratedPatches(buildDbFromLegacyHtml(html));save(db);saveRevisions([]);return db;}
  async function bootstrapLegacy(url='./data/legacy-table.html'){if(hasCurrentDataset()){const current=load();if(CURATION_VERSION>current.curationVersion&&!loadRevisions().length){const upgraded=applyCuratedPatches(current);save(upgraded);return upgraded;}return current;}try{const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error(`Legacy dataset HTTP ${res.status}`);return importLegacyHtml(await res.text());}catch(e){console.warn('Stay Atlas legacy bootstrap failed; using preview seed.',e);const fallback=applyCuratedPatches(load());save(fallback);return fallback;}}
  async function resetToLegacy(url='./data/legacy-table.html'){reset();return bootstrapLegacy(url);}
  window.StayAtlas={load,save,reset,resetToLegacy,bootstrapLegacy,loadRevisions,updateHotel,restoreRevision,addRevision,importLegacyHtml,buildDbFromLegacyHtml,applyCuratedPatches,regions,clone,diffHotel,validateHotel,health,DATASET_VERSION,CURATION_VERSION};
})();
