(function(){
  const $=s=>document.querySelector(s);
  let db={hotels:[]};let selectedId=null;
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function parseBool(raw){if(!raw)return null;if(/^[〇◯○]|あり|有/.test(raw))return true;if(/^×|なし|アクセス権なし/.test(raw))return false;return null;}
  function parseCapacity(raw){const m=(raw||'').match(/(\d+)人/);return m?Number(m[1]):null;}
  function parseChild(raw){const s=(raw||'').trim();const m=s.match(/(\d+)歳まで/);if(m)return{raw:s,allowed:true,rule_type:'age',max_age:Number(m[1])};if(/未就学児/.test(s))return{raw:s,allowed:true,rule_type:'preschool',max_age:null};if(/小学生/.test(s))return{raw:s,allowed:true,rule_type:'school_grade',max_age:null};if(/以上のみ宿泊可/.test(s))return{raw:s,allowed:false,rule_type:'minimum_age',max_age:null};return{raw:s,allowed:null,rule_type:s?'free_text':'missing',max_age:null};}
  function safeUrl(v){try{const u=new URL(v,location.href);return /^https?:$/.test(u.protocol)?u.href:'';}catch{return'';}}
  function current(){return db.hotels.find(h=>h.id===selectedId);}
  function setStatus(text,kind=''){const el=$('#liveStatus');el.textContent=text;el.className=`pill ${kind}`.trim();}
  function renderList(){const q=$('#liveSearch').value.toLowerCase();const rows=db.hotels.filter(h=>[h.name_ja,h.name_en,h.prefecture,h.chain].join(' ').toLowerCase().includes(q));$('#liveRecords').innerHTML=rows.map(h=>`<button class="admin-record ${h.id===selectedId?'is-active':''}" data-id="${esc(h.id)}"><strong>${esc(h.name_ja||'名称未登録')}</strong><br><small>${esc(h.prefecture||'—')} / ${esc(h.chain||'—')} / ${esc(h.quality||'unverified')}</small></button>`).join('')||'<p class="muted">Live DBにホテルがありません。</p>';document.querySelectorAll('#liveRecords .admin-record').forEach(b=>b.addEventListener('click',async()=>{selectedId=b.dataset.id;fill();renderList();renderVerifications();await renderRevisions();}));}
  function fill(){const h=current();if(!h)return;$('#l_id').value=h.id;$('#l_name_ja').value=h.name_ja||'';$('#l_name_en').value=h.name_en||'';$('#l_chain').value=h.chain||'Marriott Bonvoy';$('#l_brand').value=h.brand||'';$('#l_prefecture').value=h.prefecture||'';$('#l_city').value=h.city||'';$('#l_child').value=h.child?.raw||'';$('#l_capacity').value=h.capacity?.raw||'';$('#l_award').value=h.award?.raw||'';$('#l_lounge').value=h.facilities?.lounge?.raw||'';$('#l_breakfast').value=h.facilities?.breakfast?.raw||'';$('#l_onsen').value=h.facilities?.onsen?.raw||'';$('#l_pool').value=h.facilities?.pool?.raw||'';$('#l_parking').value=h.facilities?.parking?.raw||'';$('#l_quality').value=h.quality||'unverified';$('#l_checked').value=h.source?.last_checked||'';$('#l_source_url').value=h.source?.url||'';$('#l_note').value='';}
  function buildNext(){const old=current();const lounge=$('#l_lounge').value.trim(),breakfast=$('#l_breakfast').value.trim(),onsen=$('#l_onsen').value.trim(),pool=$('#l_pool').value.trim(),parking=$('#l_parking').value.trim();return{...JSON.parse(JSON.stringify(old)),name_ja:$('#l_name_ja').value.trim(),name_en:$('#l_name_en').value.trim(),chain:$('#l_chain').value,brand:$('#l_brand').value.trim(),prefecture:$('#l_prefecture').value.trim(),region:StayAtlas.regions[$('#l_prefecture').value.trim()]||'',city:$('#l_city').value.trim(),child:parseChild($('#l_child').value),capacity:{raw:$('#l_capacity').value.trim(),value:parseCapacity($('#l_capacity').value)},award:{raw:$('#l_award').value.trim()},facilities:{lounge:{raw:lounge,available:parseBool(lounge)},breakfast:{raw:breakfast,has_info:Boolean(breakfast)},onsen:{raw:onsen,available:parseBool(onsen)},pool:{raw:pool,available:parseBool(pool)},parking:{raw:parking,has_info:Boolean(parking)}},quality:$('#l_quality').value,source:{...(old.source||{}),url:$('#l_source_url').value.trim(),last_checked:$('#l_checked').value||null}};}
  function renderVerifications(){const h=current();const entries=Object.values(h?.verifications||{});$('#liveVerificationList').innerHTML=entries.length?entries.map(v=>{const url=safeUrl(v.source_url);return`<div class="verification-item"><span class="pill ${v.status==='verified'?'quality-verified':v.status==='conflicting'?'quality-needs_review':''}">${esc(v.status)}</span><div><strong>${esc(v.label||'項目')}</strong><small>${esc(v.checked_at||'日付未登録')} / ${esc(v.source_label||'Source')}</small>${v.note?`<p>${esc(v.note)}</p>`:''}${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Sourceを開く ↗</a>`:''}</div></div>`;}).join(''):'<p class="muted">Field verificationはまだありません。</p>';}
  async function renderRevisions(){if(!selectedId){$('#liveRevisionList').innerHTML='<p class="muted">ホテルを選択してください。</p>';return;}$('#liveRevisionList').innerHTML='<p class="muted">読み込み中…</p>';try{const revs=await StayAtlasSupabase.loadRevisions(selectedId);$('#liveRevisionList').innerHTML=revs.length?revs.map(r=>`<div class="revision"><strong>${esc(r.action)}</strong> <small>${esc(new Date(r.timestamp).toLocaleString('ja-JP'))}</small><p>${esc(r.note||'')}</p><button class="secondary-btn live-restore" data-rev="${esc(r.id)}" type="button">この状態を復元</button></div>`).join(''):'<p class="muted">Revisionはまだありません。</p>';document.querySelectorAll('.live-restore').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('このRevisionへ復元します。復元前の現在値も新Revisionとして残ります。'))return;try{await StayAtlasSupabase.restoreRevision(b.dataset.rev,'Live Admin restore');await reloadData(selectedId);$('#saveMessage').textContent='復元しました。復元前の状態もRevisionへ保存されています。';}catch(e){$('#saveMessage').textContent=`復元エラー: ${e.message}`;}}));}catch(e){$('#liveRevisionList').innerHTML=`<p class="muted">Revision読込エラー: ${esc(e.message)}</p>`;}}
  async function reloadData(preferId=selectedId){db=await StayAtlasSupabase.loadHotels({admin:true});selectedId=db.hotels.some(h=>h.id===preferId)?preferId:db.hotels[0]?.id||null;$('#bootstrapPanel').hidden=db.hotels.length!==0;renderList();fill();renderVerifications();await renderRevisions();}
  async function enterWorkspace(user){setStatus('LIVE DB','quality-verified');$('#connectionNote').textContent='Supabase Auth + RLSで接続中です。BrowserにはPublishable Keyのみを使用し、書込権限はDB側のAdmin RLSで判定します。';$('#liveUser').textContent=user.email||user.id;$('#loginPanel').hidden=true;$('#liveWorkspace').hidden=false;await reloadData();}
  async function showAuth(){const state=await StayAtlasSupabase.authState();if(!state.configured){setStatus('NOT CONFIGURED');$('#connectionNote').textContent='Supabase Projectはまだ接続されていません。supabase-config.js にProject URLとPublishable Keyを設定するとLive Adminが有効になります。Secret key / service_role keyはBrowserへ置かないでください。';$('#loginPanel').hidden=true;$('#liveWorkspace').hidden=true;return;}if(state.user&&state.isAdmin){await enterWorkspace(state.user);return;}setStatus(state.user?'NOT ADMIN':'AUTH REQUIRED');$('#connectionNote').textContent=state.user?'ログイン済みですが stay_atlas_role=admin がありません。DB書込はRLSで拒否されます。':'Supabase管理者アカウントでログインしてください。';$('#loginPanel').hidden=false;$('#liveWorkspace').hidden=true;}
  $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginMessage').textContent='ログイン中…';try{const result=await StayAtlasSupabase.signIn($('#loginEmail').value.trim(),$('#loginPassword').value);if(!result.isAdmin){$('#loginMessage').textContent='認証は成功しましたが、Stay Atlas Admin権限がありません。';await showAuth();return;}$('#loginMessage').textContent='';await enterWorkspace(result.user);}catch(err){$('#loginMessage').textContent=`ログインエラー: ${err.message}`;}});
  $('#logoutBtn').addEventListener('click',async()=>{await StayAtlasSupabase.signOut();await showAuth();});$('#reloadBtn').addEventListener('click',()=>reloadData());$('#liveSearch').addEventListener('input',renderList);
  $('#bootstrapBtn').addEventListener('click',async()=>{if(!confirm('Live DBが空であることを確認し、旧表＋公式確認Patchから初期Datasetを投入します。実行しますか？'))return;const btn=$('#bootstrapBtn');btn.disabled=true;$('#bootstrapMessage').textContent='初期Datasetを構築中…';try{const response=await fetch('./data/legacy-table.html',{cache:'no-store'});if(!response.ok)throw new Error(`Legacy source HTTP ${response.status}`);const raw=StayAtlas.buildDbFromLegacyHtml(await response.text());const preview=StayAtlas.applyCuratedPatches(raw);const result=await StayAtlasSupabaseBootstrap.bootstrapFromPreview(preview);$('#bootstrapMessage').textContent=`${result.hotelCount} hotels / ${result.verificationCount} field verifications を投入しました。`;await reloadData();}catch(e){$('#bootstrapMessage').textContent=`初期投入エラー: ${e.message}`;}finally{btn.disabled=false;}});
  $('#liveSaveBtn').addEventListener('click',async()=>{if(!selectedId)return;const next=buildNext();if(!next.name_ja){$('#saveMessage').textContent='ホテル名（日本語）は必須です。';return;}$('#saveMessage').textContent='保存中…';try{await StayAtlasSupabase.updateHotel(selectedId,next,$('#l_note').value.trim()||'Live Admin edit');await reloadData(selectedId);$('#saveMessage').textContent='DBへ保存しました。変更前の状態はRevisionに保持されています。';}catch(e){$('#saveMessage').textContent=`保存エラー: ${e.message}`;}});
  showAuth().catch(e=>{setStatus('ERROR');$('#connectionNote').textContent=`接続確認エラー: ${e.message}`;});
})();
